┏━━━┳━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name    ┃ Type      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ model   │ Segformer │ 13.7 M │ train │
│ 1 │ loss_fn │ DiceLoss  │      0 │ train │
└───┴─────────┴───────────┴────────┴───────┘
Trainable params: 526 K
Non-trainable params: 13.2 M
Total params: 13.7 M
Total estimated model params size (MB): 54
Modules in train mode: 194
Modules in eval mode: 0
Z:\Miniconda\envs\ml-env\lib\site-packages\torch\optim\lr_scheduler.py:240: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where     
possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form,     
where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
Epoch 0/34 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 749/749 0:02:48 • 0:00:00 4.49it/s v_num: eduu valid_per_image_iou: 0.653 valid_dataset_iou: 0.607
[W 2025-06-11 14:05:41,530] Trial 0 failed with parameters: {'encoder_name': 'mit_b1', 'scheduler_type': 'CosineAnnealingLR', 'batch_size': 16, 'warmup_steps': 500, 'lr': 4.432679705976732e-05, 'weight_decay': 0.0011990060706343344, 'drop_path_rate': 0.0589290714641007} because of the following error: RuntimeError('torch.cat(): expected a non-empty list of Tensors').
Traceback (most recent call last):
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "Z:\tree-tornado\src\model.py", line 537, in objective
    trainer.fit(model, train_dataloaders=train_loader, val_dataloaders=val_loader)
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1012, in _run
    results = self._run_stage()
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1056, in _run_stage
    self.fit_loop.run()
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 217, in run
    self.on_advance_end()
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 469, in on_advance_end
    call._call_lightning_module_hook(trainer, "on_train_epoch_end")
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\call.py", line 176, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "Z:\tree-tornado\src\model.py", line 414, in on_train_epoch_end
    self.shared_epoch_end(self.training_step_outputs, "train")
  File "Z:\tree-tornado\src\model.py", line 394, in shared_epoch_end
    tp = torch.cat([x["tp"] for x in outputs])
RuntimeError: torch.cat(): expected a non-empty list of Tensors
[W 2025-06-11 14:05:41,543] Trial 0 failed with value None.
Traceback (most recent call last):
  File "Z:\tree-tornado\src\model.py", line 565, in <module>
    study.optimize(objective, n_trials=100, timeout=3600*6) # Run for 100 trials or 6 hours
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\optuna\study\study.py", line 475, in optimize
    _optimize(
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\optuna\study\_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\optuna\study\_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\optuna\study\_optimize.py", line 248, in _run_trial
    raise func_err
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "Z:\tree-tornado\src\model.py", line 537, in objective
    trainer.fit(model, train_dataloaders=train_loader, val_dataloaders=val_loader)
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1012, in _run
    results = self._run_stage()
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1056, in _run_stage
    self.fit_loop.run()
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 217, in run
    self.on_advance_end()
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 469, in on_advance_end
    call._call_lightning_module_hook(trainer, "on_train_epoch_end")
  File "Z:\Miniconda\envs\ml-env\lib\site-packages\lightning\pytorch\trainer\call.py", line 176, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "Z:\tree-tornado\src\model.py", line 414, in on_train_epoch_end
    self.shared_epoch_end(self.training_step_outputs, "train")
  File "Z:\tree-tornado\src\model.py", line 394, in shared_epoch_end
    tp = torch.cat([x["tp"] for x in outputs])
RuntimeError: torch.cat(): expected a non-empty list of Tensors